"""updates user and interview with scores

Revision ID: 0aa1865f1a19
Revises: bb73ed79a4ea
Create Date: 2025-04-29 11:16:55.655107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa1865f1a19'
down_revision: Union[str, None] = 'bb73ed79a4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_feedback', sa.Column('clarity_level', sa.Integer(), nullable=False))
    op.add_column('interview_feedback', sa.Column('structure_level', sa.Integer(), nullable=False))
    op.add_column('interview_feedback', sa.Column('communication_level', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'interview_feedback', 'competency_levels', ['structure_level'], ['id'])
    op.create_foreign_key(None, 'interview_feedback', 'competency_levels', ['communication_level'], ['id'])
    op.create_foreign_key(None, 'interview_feedback', 'competency_levels', ['clarity_level'], ['id'])
    op.add_column('users', sa.Column('clarity_level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('structure_level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('communication_level', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'competency_levels', ['communication_level'], ['id'])
    op.create_foreign_key(None, 'users', 'competency_levels', ['clarity_level'], ['id'])
    op.create_foreign_key(None, 'users', 'competency_levels', ['structure_level'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'communication_level')
    op.drop_column('users', 'structure_level')
    op.drop_column('users', 'clarity_level')
    op.drop_constraint(None, 'interview_feedback', type_='foreignkey')
    op.drop_constraint(None, 'interview_feedback', type_='foreignkey')
    op.drop_constraint(None, 'interview_feedback', type_='foreignkey')
    op.drop_column('interview_feedback', 'communication_level')
    op.drop_column('interview_feedback', 'structure_level')
    op.drop_column('interview_feedback', 'clarity_level')
    # ### end Alembic commands ###
