"""adds interview feedback

Revision ID: 574fb0985b03
Revises: fe141133eb60
Create Date: 2025-04-29 10:05:30.998888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574fb0985b03'
down_revision: Union[str, None] = 'fe141133eb60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_feedback',
    sa.Column('clarity', sa.Double(), nullable=False),
    sa.Column('structure', sa.Double(), nullable=False),
    sa.Column('communication', sa.Double(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('general_score', sa.Double(), nullable=False),
    sa.Column('recommendations', sa.String(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedback_id'), 'interview_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_feedback_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    # ### end Alembic commands ###
