"""Initial migration

Revision ID: 6ec32a46a89e
Revises: 
Create Date: 2025-05-01 20:06:47.756483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec32a46a89e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competency', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_levels_id'), 'competency_levels', ['id'], unique=False)
    op.create_table('mistake_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistake_categories_id'), 'mistake_categories', ['id'], unique=False)
    op.create_table('question_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_categories_id'), 'question_categories', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['question_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('b2c', sa.Boolean(), nullable=False),
    sa.Column('interview_count', sa.Integer(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('clarity_level', sa.Integer(), nullable=False),
    sa.Column('structure_level', sa.Integer(), nullable=False),
    sa.Column('communication_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clarity_level'], ['competency_levels.id'], ),
    sa.ForeignKeyConstraint(['communication_level'], ['competency_levels.id'], ),
    sa.ForeignKeyConstraint(['structure_level'], ['competency_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('general_score', sa.Double(), nullable=False),
    sa.Column('recommendations', sa.String(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('clarity_level', sa.Integer(), nullable=False),
    sa.Column('structure_level', sa.Integer(), nullable=False),
    sa.Column('communication_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clarity_level'], ['competency_levels.id'], ),
    sa.ForeignKeyConstraint(['communication_level'], ['competency_levels.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['structure_level'], ['competency_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedback_id'), 'interview_feedback', ['id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_table('interview_mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['mistake_categories.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interview_feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_mistakes_id'), 'interview_mistakes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_mistakes_id'), table_name='interview_mistakes')
    op.drop_table('interview_mistakes')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interview_feedback_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_categories_id'), table_name='question_categories')
    op.drop_table('question_categories')
    op.drop_index(op.f('ix_mistake_categories_id'), table_name='mistake_categories')
    op.drop_table('mistake_categories')
    op.drop_index(op.f('ix_competency_levels_id'), table_name='competency_levels')
    op.drop_table('competency_levels')
    # ### end Alembic commands ###
