"""updates interview feedback

Revision ID: bb73ed79a4ea
Revises: ab34566a82b1
Create Date: 2025-04-29 10:14:19.893498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb73ed79a4ea'
down_revision: Union[str, None] = 'ab34566a82b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_feedback', 'clarity')
    op.drop_column('interview_feedback', 'structure')
    op.drop_column('interview_feedback', 'communication')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_feedback', sa.Column('communication', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('interview_feedback', sa.Column('structure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('interview_feedback', sa.Column('clarity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
