"""add new columns to interviewquestions

Revision ID: cb94dca07340
Revises: dd216fc23b43
Create Date: 2025-05-13 01:17:44.417400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb94dca07340'
down_revision: Union[str, None] = 'dd216fc23b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'answer')
    # ### end Alembic commands ###
