"""add new column to model

Revision ID: d0dfea5c20c3
Revises: f3819d8fdc43
Create Date: 2025-05-12 20:28:41.535516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0dfea5c20c3'
down_revision: Union[str, None] = 'f3819d8fdc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interview_questions', sa.Column('answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'answer')
    op.drop_column('interview_questions', 'answered_at')
    # ### end Alembic commands ###
