"""add new columns to interviewquestions

Revision ID: dd216fc23b43
Revises: d0dfea5c20c3
Create Date: 2025-05-13 00:39:01.437772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd216fc23b43'
down_revision: Union[str, None] = 'd0dfea5c20c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('clarity_score', sa.Integer(), nullable=True))
    op.add_column('interview_questions', sa.Column('structure_score', sa.Integer(), nullable=True))
    op.add_column('interview_questions', sa.Column('communication_score', sa.Integer(), nullable=True))
    op.add_column('interview_questions', sa.Column('overall_score', sa.Integer(), nullable=True))
    op.add_column('interview_questions', sa.Column('feedback', sa.String(), nullable=True))
    op.drop_column('interview_questions', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('interview_questions', 'feedback')
    op.drop_column('interview_questions', 'overall_score')
    op.drop_column('interview_questions', 'communication_score')
    op.drop_column('interview_questions', 'structure_score')
    op.drop_column('interview_questions', 'clarity_score')
    # ### end Alembic commands ###
