"""add new entities

Revision ID: e18dc4570035
Revises: 6bfcc1947188
Create Date: 2025-04-28 21:21:17.188776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18dc4570035'
down_revision: Union[str, None] = '6bfcc1947188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('b2c', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('interview_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('linkedin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'interview_count')
    op.drop_column('users', 'b2c')
    # ### end Alembic commands ###
