"""removes overall score from interview question

Revision ID: ead69153d543
Revises: cb94dca07340
Create Date: 2025-05-13 01:36:48.279701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead69153d543'
down_revision: Union[str, None] = 'cb94dca07340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'overall_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
